import 'package:flutter/material.dart';

class ThemeClass {
  static ThemeData lightTheme(String selectedFont) {
    return ThemeData(
      fontFamily: selectedFont,
      colorScheme: const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF006E22),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFF91FA95),
        onPrimaryContainer: Color(0xFF002105),
        secondary: Color(0xFF745B00),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFFFE08B),
        onSecondaryContainer: Color(0xFF241A00),
        tertiary: Color(0xFFB82013),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFFFDAD4),
        onTertiaryContainer: Color(0xFF410000),
        error: Color(0xFFBA1A1A),
        errorContainer: Color(0xFFFFDAD6),
        onError: Color(0xFFFFFFFF),
        onErrorContainer: Color(0xFF410002),
        background: Color(0xFFF8FDFF),
        onBackground: Color(0xFF001F25),
        surface: Color(0xFFF8FDFF),
        onSurface: Color(0xFF001F25),
        surfaceVariant: Color(0xFFDEE5D9),
        onSurfaceVariant: Color(0xFF424940),
        outline: Color(0xFF72796F),
        onInverseSurface: Color(0xFFD6F6FF),
        inverseSurface: Color(0xFF00363F),
        inversePrimary: Color(0xFF76DC7B),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF006E22),
        outlineVariant: Color(0xFFC2C9BD),
        scrim: Color(0xFF000000),
      ),
    );
  }

  static ThemeData darkTheme(String selectedFont) {
    return ThemeData(
      fontFamily: selectedFont,
      colorScheme: const ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFF76DC7B),
        onPrimary: Color(0xFF00390E),
        primaryContainer: Color(0xFF005318),
        onPrimaryContainer: Color(0xFF91FA95),
        secondary: Color(0xFFF1C100),
        onSecondary: Color(0xFF3D2F00),
        secondaryContainer: Color(0xFF584400),
        onSecondaryContainer: Color(0xFFFFE08B),
        tertiary: Color(0xFFFFB4A8),
        onTertiary: Color(0xFF690100),
        tertiaryContainer: Color(0xFF930100),
        onTertiaryContainer: Color(0xFFFFDAD4),
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        background: Color(0xFF001F25),
        onBackground: Color(0xFFA6EEFF),
        surface: Color(0xFF001F25),
        onSurface: Color(0xFFA6EEFF),
        surfaceVariant: Color(0xFF424940),
        onSurfaceVariant: Color(0xFFC2C9BD),
        outline: Color(0xFF8C9388),
        onInverseSurface: Color(0xFF001F25),
        inverseSurface: Color(0xFFA6EEFF),
        inversePrimary: Color(0xFF006E22),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF76DC7B),
        outlineVariant: Color(0xFF424940),
        scrim: Color(0xFF000000),
      ),
    );
  }
}
